In [23]:
import numpy as np
from exact_diagonalization import exact_diagonalization

In [24]:
def generate_symmetric_matrix(n):
    A = np.empty((n, n), dtype=float)
    
    visited = []
    for i in range(n):
        for j in range(n):
            
            if (i, j) in visited:
                continue
                
            rand_num = np.random.rand()
            
            if i != j:
                A[i, j] = rand_num
                A[j, i] = rand_num
                visited.append((j, i))
            else:
                A[i, i] = rand_num
                
    return A


def error(A, B):
    return np.sum((A - B)**2)

In [27]:
A = generate_symmetric_matrix(3)
Q, T, Q_inv = exact_diagonalization(A)
reconstructed_A = Q @ T @ Q_inv

print(f"Matrix: \n {A}", end="\n\n")
print(f"Reconstructed: \n {reconstructed_A}")
print(f"Error: {error(A, reconstructed_A)}")

Matrix: 
 [[0.05507638 0.27158477 0.15711041]
 [0.27158477 0.26288203 0.46852157]
 [0.15711041 0.46852157 0.49846683]]

Reconstructed: 
 [[0.05507638 0.27158477 0.15711041]
 [0.27158477 0.26288203 0.46852157]
 [0.15711041 0.46852157 0.49846683]]
Error: 4.4631500531229804e-29


In [28]:
A = generate_symmetric_matrix(10)
Q, T, Q_inv = exact_diagonalization(A)
reconstructed_A = Q @ T @ Q_inv

print(f"Matrix: \n {A}", end="\n\n")
print(f"Reconstructed: \n {reconstructed_A}", end="\n\n")
print(f"Error: {error(A, reconstructed_A)}")

Matrix: 
 [[0.02901716 0.8400012  0.46036963 0.27534251 0.69933207 0.98275829
  0.5366234  0.69384401 0.73655031 0.95793076]
 [0.8400012  0.66928011 0.89142141 0.95824127 0.98729921 0.4478202
  0.65255197 0.44055531 0.41391258 0.87929097]
 [0.46036963 0.89142141 0.15078238 0.42862802 0.49744066 0.01672111
  0.37558426 0.78924849 0.50633667 0.21113713]
 [0.27534251 0.95824127 0.42862802 0.30563469 0.5523128  0.65599998
  0.72816127 0.81523577 0.21716694 0.67512594]
 [0.69933207 0.98729921 0.49744066 0.5523128  0.68593304 0.10171932
  0.17375678 0.45299754 0.36755016 0.21550285]
 [0.98275829 0.4478202  0.01672111 0.65599998 0.10171932 0.71660803
  0.77582594 0.33703601 0.5495502  0.54630197]
 [0.5366234  0.65255197 0.37558426 0.72816127 0.17375678 0.77582594
  0.36568984 0.98411278 0.39405567 0.57262969]
 [0.69384401 0.44055531 0.78924849 0.81523577 0.45299754 0.33703601
  0.98411278 0.29143227 0.69530523 0.99031526]
 [0.73655031 0.41391258 0.50633667 0.21716694 0.36755016 0.5495502
  0.

In [ ]:
A = generate_symmetric_matrix(10000)
Q, T, Q_inv = exact_diagonalization(A)
reconstructed_A = Q @ T @ Q_inv

print(f"Matrix: \n {A}", end="\n\n")
print(f"Reconstructed: \n {reconstructed_A}", end="\n\n")
print(f"Error: {error(A, reconstructed_A)}")