In [1]:
import numpy as np
from exact_diagonalization import exact_diagonalization

In [6]:
def generate_symmetric_matrix(n):
    A = np.empty((n, n), dtype=float)
    
    visited = []
    for i in range(n):
        for j in range(n):
            
            if (i, j) in visited:
                continue
                
            rand_num = np.random.rand()
            
            if i != j:
                A[i, j] = rand_num
                A[j, i] = rand_num
                visited.append((j, i))
            else:
                A[i, i] = rand_num
                
    return A


def error(A, B):
    return np.average((A - B)**2)

In [7]:
A = generate_symmetric_matrix(3)
Q, T, Q_inv = exact_diagonalization(A)
reconstructed_A = Q @ T @ Q_inv

print(f"Matrix: \n {A}", end="\n\n")
print(f"Reconstructed: \n {reconstructed_A}")
print(f"Error: {error(A, reconstructed_A)}")

Matrix: 
 [[0.25333969 0.37982139 0.89997224]
 [0.37982139 0.29969489 0.77737422]
 [0.89997224 0.77737422 0.11974533]]

Reconstructed: 
 [[0.25333969 0.37982139 0.89997224]
 [0.37982139 0.29969489 0.77737422]
 [0.89997224 0.77737422 0.11974533]]
Error: 4.458078437602761e-30


In [8]:
A = generate_symmetric_matrix(10)
Q, T, Q_inv = exact_diagonalization(A)
reconstructed_A = Q @ T @ Q_inv

print(f"Matrix: \n {A}", end="\n\n")
print(f"Reconstructed: \n {reconstructed_A}", end="\n\n")
print(f"Error: {error(A, reconstructed_A)}")

Matrix: 
 [[0.11026395 0.78092719 0.28188857 0.00892211 0.83759865 0.53630194
  0.75058547 0.01144098 0.78967646 0.34017598]
 [0.78092719 0.48819246 0.50811184 0.45348794 0.19014487 0.84629508
  0.56643967 0.08921941 0.48582813 0.51826086]
 [0.28188857 0.50811184 0.38210328 0.11794482 0.20023593 0.79718938
  0.9768654  0.54380625 0.94852703 0.79005021]
 [0.00892211 0.45348794 0.11794482 0.88414601 0.82786853 0.77911179
  0.18320865 0.99663925 0.72747223 0.87452791]
 [0.83759865 0.19014487 0.20023593 0.82786853 0.06474799 0.80793431
  0.78125466 0.85565218 0.38706208 0.7739435 ]
 [0.53630194 0.84629508 0.79718938 0.77911179 0.80793431 0.50530561
  0.35182344 0.65485718 0.34730077 0.92053849]
 [0.75058547 0.56643967 0.9768654  0.18320865 0.78125466 0.35182344
  0.38977349 0.17832994 0.39194055 0.5484263 ]
 [0.01144098 0.08921941 0.54380625 0.99663925 0.85565218 0.65485718
  0.17832994 0.55849993 0.21478912 0.11995633]
 [0.78967646 0.48582813 0.94852703 0.72747223 0.38706208 0.34730077
  

In [9]:
A = generate_symmetric_matrix(30)
Q, T, Q_inv = exact_diagonalization(A)
reconstructed_A = Q @ T @ Q_inv

print(f"Matrix: \n {A}", end="\n\n")
print(f"Reconstructed: \n {reconstructed_A}", end="\n\n")
print(f"Error: {error(A, reconstructed_A)}")

Matrix: 
 [[0.02703799 0.36117414 0.5276769  0.44594876 0.24838765 0.41719925
  0.0612156  0.73790579 0.75722065 0.00384489 0.62397158 0.60669215
  0.57582577 0.14233026 0.46117443 0.74285244 0.01089306 0.62672873
  0.91599274 0.78842791 0.73003881 0.49052567 0.70321806 0.33702028
  0.350582   0.6041677  0.74551448 0.66382032 0.77195555 0.55060701]
 [0.36117414 0.57697846 0.4183316  0.42420937 0.2238731  0.97505252
  0.70799262 0.95878523 0.68489668 0.71409399 0.63467812 0.7088891
  0.32520436 0.56757055 0.10485843 0.49301609 0.29943079 0.08398084
  0.10864648 0.93211506 0.87580268 0.94212295 0.67610709 0.88892474
  0.91205255 0.09484937 0.89718841 0.30311208 0.49367644 0.31904848]
 [0.5276769  0.4183316  0.47444292 0.88551649 0.66452526 0.17098296
  0.73262971 0.85985999 0.31483187 0.22104657 0.36893873 0.95621235
  0.26862239 0.61016    0.02110587 0.8123641  0.13217187 0.30149488
  0.92481729 0.46431393 0.17909794 0.55251742 0.76761973 0.42652488
  0.45777268 0.55831801 0.88106785 0.