In [1]:
import numpy as np
from qr import qr_decomposition

In [4]:
A = np.array([[5, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [6]:
Q, R = qr_decomposition(A)
Q, R

(array([[ 0.52704628, -0.8443826 ,  0.0961262 ],
        [ 0.42163702,  0.35801822,  0.83309374],
        [ 0.73786479,  0.39854859, -0.54471514]]),
 array([[ 9.48683298e+00,  9.06519596e+00,  1.07517440e+01],
        [-2.22044605e-15,  3.28971461e+00,  3.20189882e+00],
        [ 5.32907052e-15,  6.21724894e-15,  3.84504802e-01]]))

In [7]:
Q @ R

array([[5., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])